-- Creating the database
CREATE DATABASE superprice;
USE superprice;

-- PRODUCT table
CREATE TABLE PRODUCT (
    ProductID INT AUTO_INCREMENT PRIMARY KEY,
    ProductName VARCHAR(255) NOT NULL,
    Description TEXT,
    Price DECIMAL(10, 2) NOT NULL,
    Availability BOOLEAN NOT NULL,
    ImageURL VARCHAR(255),
    LastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- CATEGORY table
CREATE TABLE CATEGORY (
    CategoryID INT AUTO_INCREMENT PRIMARY KEY,
    CategoryName VARCHAR(255) NOT NULL UNIQUE
);

-- STORE table
CREATE TABLE STORE (
    StoreID INT AUTO_INCREMENT PRIMARY KEY,
    StoreName VARCHAR(255) NOT NULL,
    StoreLocation VARCHAR(255) NOT NULL,
    ContactDetails VARCHAR(255)
);

-- USER table
CREATE TABLE USER (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(255) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,
    Address VARCHAR(255)
);

-- REVIEW table
CREATE TABLE REVIEW (
    ReviewID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT,
    ProductID INT,
    Rating INT NOT NULL,
    Comment TEXT,
    FOREIGN KEY (UserID) REFERENCES USER(UserID),
    FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID)
);

-- TRANSACTION table
CREATE TABLE TRANSACTION (
    TransactionID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT,
    TransactionDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TotalAmount DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (UserID) REFERENCES USER(UserID)
);

-- TRANSACTION_ITEM table
CREATE TABLE TRANSACTION_ITEM (
    TransactionItemID INT AUTO_INCREMENT PRIMARY KEY,
    TransactionID INT,
    ProductID INT,
    Quantity INT NOT NULL,
    SubTotal DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (TransactionID) REFERENCES TRANSACTION(TransactionID),
    FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID)
);

-- NOTIFICATION table
CREATE TABLE NOTIFICATION (
    NotificationID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT,
    Message TEXT NOT NULL,
    DateSent TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES USER(UserID)
);

-- CART_ITEM table
CREATE TABLE CART_ITEM (
    CartItemID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT,
    ProductID INT,
    Quantity INT NOT NULL,
    FOREIGN KEY (UserID) REFERENCES USER(UserID),
    FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID)
);

-- PRODUCT_CATEGORY association table
CREATE TABLE PRODUCT_CATEGORY (
    ProductCategoryID INT AUTO_INCREMENT PRIMARY KEY,
    ProductID INT,
    CategoryID INT,
    FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID),
    FOREIGN KEY (CategoryID) REFERENCES CATEGORY(CategoryID)
);

-- PRODUCT_STORE association table
CREATE TABLE PRODUCT_STORE (
    ProductStoreID INT AUTO_INCREMENT PRIMARY KEY,
    ProductID INT,
    StoreID INT,
    FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID),
    FOREIGN KEY (StoreID) REFERENCES STORE(StoreID)
);
