name: Team Group-P2-07 CI tasks
on:
  push:
     branches:
      - main
jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        working-directory: backend
        run: chmod +x mvnw && ./mvnw --batch-mode --update-snapshots package
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Using Node js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Frontend Tests
        working-directory: frontend
        run: npm ci
      - run: npm test
        working-directory: frontend
